// <auto-generated />
using Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infraestructure.Migrations
{
    [DbContext(typeof(EntidadContext))]
    [Migration("20191107162108_MigracionInical")]
    partial class MigracionInical
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entidades.Credito", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Cedula")
                        .HasColumnType("bigint");

                    b.Property<string>("FechaPrestamo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlazoPago")
                        .HasColumnType("int");

                    b.Property<float>("ValorPrestamo")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Credito");
                });

            modelBuilder.Entity("Domain.Entidades.Cuota", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreditoId")
                        .HasColumnType("int");

                    b.Property<int>("MesCuota")
                        .HasColumnType("int");

                    b.Property<float>("ValorCuota")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("CreditoId");

                    b.ToTable("Cuota");
                });

            modelBuilder.Entity("Domain.Entidades.Cuota", b =>
                {
                    b.HasOne("Domain.Entidades.Credito", null)
                        .WithMany("Cuotas")
                        .HasForeignKey("CreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
